import KanbanCodeCore
import Testing

@testable import KanbanCode

@MainActor
@Suite("Jumping back to the previous user message")
struct ChatPreviousMessageTests {

    private static func user(_ lineNumber: Int, _ text: String = "do the thing")
        -> ConversationTurn
    {
        ConversationTurn(
            index: lineNumber, lineNumber: lineNumber, role: "user", textPreview: text,
            contentBlocks: [ContentBlock(kind: .text, text: text)]
        )
    }

    private static func assistant(_ lineNumber: Int) -> ConversationTurn {
        ConversationTurn(
            index: lineNumber, lineNumber: lineNumber, role: "assistant", textPreview: "ok",
            contentBlocks: [ContentBlock(kind: .text, text: "ok")]
        )
    }

    /// A user turn that only carries the result of a tool call. It is the
    /// record of the assistant's own work, not something anybody typed.
    private static func toolResult(_ lineNumber: Int) -> ConversationTurn {
        ConversationTurn(
            index: lineNumber, lineNumber: lineNumber, role: "user", textPreview: "",
            contentBlocks: [
                ContentBlock(kind: .toolResult(toolName: "Read", toolUseId: "t1"), text: "file body")
            ]
        )
    }

    @Test("the jump lands on the message before the top of the view")
    func picksTheOneAbove() {
        let turns = [
            Self.user(10), Self.assistant(20), Self.user(30), Self.assistant(40),
        ]

        let target = ChatTranscript.previousUserTurn(in: turns, above: 35)

        #expect(target?.lineNumber == 30)
    }

    @Test("pressing again walks back another message")
    func walksBack() {
        let turns = [
            Self.user(10), Self.assistant(20), Self.user(30), Self.assistant(40),
        ]

        let first = ChatTranscript.previousUserTurn(in: turns, above: 40)
        let second = ChatTranscript.previousUserTurn(in: turns, above: first!.lineNumber)

        #expect(first?.lineNumber == 30)
        #expect(second?.lineNumber == 10)
    }

    @Test("the message at the top of the view is not the one jumped to")
    func strictlyAbove() {
        let turns = [Self.user(10), Self.user(30)]

        #expect(ChatTranscript.previousUserTurn(in: turns, above: 30)?.lineNumber == 10)
    }

    @Test("a tool result is not a message you asked for")
    func skipsToolResults() {
        let turns = [
            Self.user(10), Self.assistant(20), Self.toolResult(30), Self.assistant(40),
        ]

        #expect(ChatTranscript.previousUserTurn(in: turns, above: 45)?.lineNumber == 10)
    }

    @Test("an assistant message is never the target")
    func skipsAssistantTurns() {
        let turns = [Self.assistant(10), Self.assistant(20)]

        #expect(ChatTranscript.previousUserTurn(in: turns, above: 25) == nil)
    }

    @Test("nothing loaded that far back reports none, so history can be read")
    func nothingAbove() {
        let turns = [Self.user(50), Self.assistant(60)]

        #expect(ChatTranscript.previousUserTurn(in: turns, above: 50) == nil)
    }

    private static func userText(_ text: String) -> ConversationTurn {
        ConversationTurn(
            index: 1, lineNumber: 100, role: "user", textPreview: text,
            contentBlocks: [ContentBlock(kind: .text, text: text)]
        )
    }

    @Test("what the person typed is a message")
    func typedMessageCounts() {
        #expect(ChatTranscript.isTypedMessage(Self.userText("can you fix the login flow")))
    }

    @Test("an agent reporting in is not a message")
    func taskNotificationSkipped() {
        #expect(!ChatTranscript.isTypedMessage(Self.userText("✓ Agent \"Fix the flake\" finished")))
        #expect(!ChatTranscript.isTypedMessage(Self.userText("⏳ Agent \"Fix the flake\" started")))
    }

    @Test("the note left where a run was stopped is not a message")
    func interruptionSkipped() {
        #expect(
            !ChatTranscript.isTypedMessage(
                Self.userText("[Request interrupted by user for tool use]")))
    }

    @Test("the wrapper around a slash command is not a message")
    func commandWrapperSkipped() {
        let wrapper = """
            <command-name>/compact</command-name>
            <command-message>compact</command-message>
            <command-args></command-args>
            """
        #expect(!ChatTranscript.isTypedMessage(Self.userText(wrapper)))
    }

    @Test("a caveat the harness writes is not a message")
    func caveatSkipped() {
        let caveat =
            "Caveat: The messages below were generated by the user while running local commands."
        #expect(!ChatTranscript.isTypedMessage(Self.userText(caveat)))
    }

    @Test("a reminder the harness injects is not a message")
    func systemReminderSkipped() {
        let reminder = "<system-reminder>The task list is empty.</system-reminder>"
        #expect(!ChatTranscript.isTypedMessage(Self.userText(reminder)))
    }

    @Test("a message with a reminder stuck on the end is still a message")
    func textWithReminderCounts() {
        let text = "run the tests\n<system-reminder>Be careful.</system-reminder>"
        #expect(ChatTranscript.isTypedMessage(Self.userText(text)))
    }

    @Test("the assistant's own turns are never messages you typed")
    func assistantSkipped() {
        #expect(!ChatTranscript.isTypedMessage(Self.assistant(10)))
    }

    @Test("a jump passes over everything the harness wrote")
    func jumpSkipsSystemTurns() {
        let turns = [
            Self.user(10, "the real question"),
            Self.assistant(20),
            ConversationTurn(
                index: 3, lineNumber: 30, role: "user", textPreview: "",
                contentBlocks: [ContentBlock(kind: .text, text: "✓ Agent \"Build\" finished")]
            ),
            ConversationTurn(
                index: 4, lineNumber: 40, role: "user", textPreview: "",
                contentBlocks: [
                    ContentBlock(kind: .text, text: "[Request interrupted by user]")
                ]
            ),
        ]

        #expect(ChatTranscript.previousUserTurn(in: turns, above: 50)?.lineNumber == 10)
    }

    @Test("the topmost row on screen is what the jump measures from")
    func visibleRowsReportTheTop() {
        let rows = ChatVisibleRows()

        let mounted: Set<Int> = [100, 200, 300]
        rows.set(300, visible: true)
        rows.set(100, visible: true)
        rows.set(200, visible: true)
        #expect(rows.top(among: mounted) == 100)

        rows.set(100, visible: false)
        #expect(rows.top(among: mounted) == 200)
    }

    @Test("a row aimed at holds the top until the scroll catches up")
    func pinnedTopWins() {
        let rows = ChatVisibleRows()
        rows.set(300, visible: true)

        rows.pinTop(80)

        #expect(rows.top(among: [300]) == 80)
    }

    /// A row the list has dropped as the window moved has no way to say it
    /// left, so a stale one must not decide where the jump starts.
    @Test("a row that is no longer in the list does not count as on screen")
    func staleRowsAreIgnored() {
        let rows = ChatVisibleRows()
        rows.set(10, visible: true)
        rows.set(400, visible: true)

        #expect(rows.top(among: [400, 500]) == 400)
    }

    @Test("an empty view measures from nothing")
    func emptyTracker() {
        #expect(ChatVisibleRows().top(among: [1, 2, 3]) == nil)
    }
}
